// src/components/Header.tsx
import React from 'react';

const Header: React.FC = () => {
  return (
    <header className="bg-white shadow-sm">
      <nav className="container mx-auto px-4 py-4">
        <div className="flex justify-between items-center">
          <h1 className="text-2xl font-bold text-gray-800">Portfolio</h1>
          <div className="space-x-6">
            <a href="#about" className="text-gray-600 hover:text-gray-900">About</a>
            <a href="#projects" className="text-gray-600 hover:text-gray-900">Projects</a>
            <a href="#contact" className="text-gray-600 hover:text-gray-900">Contact</a>
          </div>
        </div>
      </nav>
    </header>
  );
};

export default Header;

// src/components/Header.vue
<template>
  <header class="bg-white shadow-sm">
    <nav class="container mx-auto px-4 py-4">
      <div class="flex justify-between items-center">
        <h1 class="text-2xl font-bold text-gray-800">Portfolio</h1>
        <div class="space-x-6">
          <a href="#about" class="text-gray-600 hover:text-gray-900">About</a>
          <a href="#projects" class="text-gray-600 hover:text-gray-900">Projects</a>
          <a href="#contact" class="text-gray-600 hover:text-gray-900">Contact</a>
        </div>
      </div>
    </nav>
  </header>
</template>

<script setup lang="ts">
// コンポーネントのロジックはここに記述
</script>
